eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8001
spring:
  application:
    name: service-client

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"