#eureka服务器地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

#本服务端口号
server:
  port: 8002

#应用名称
spring:
  application:
    name: service-consumer

  #zipkin服务地址
  zipkin:
    base-url: http://localhost:9411